FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:bullseye

RUN apt update && apt upgrade -y
RUN curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
RUN apt install -y gcc g++ make build-essential nodejs sox gstreamer1.0-tools gstreamer1.0-plugins-good gstreamer1.0-plugins-base gstreamer1.0-plugins-base-apps
RUN npm config set user root && npm install edge-impulse-linux -g --unsafe-perm

CMD ["sleep", "infinity"]
